version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dvdrental.tar:/tmp/dvdrental.tar
    ports:
      - "5435:5432"
